### ISSUE TITLE
Compile all MMR helper functions from twenty-first

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/tasm-lang#12]
This compiler should be able to handle all MMR helper functions that can be found in `twenty-first/src/util_types/mmr/shared.rs`. The `u128` values should be converted to `u64` instead though, as `u64::MAX` is more than enough for our use case.

Also: Please note that you can rewrite the algorithms to something the compiler can handle. If the algorithm was e.g. written with a `loop` statement, this can be rewritten to a `while(true)` or something similar.

**Comment by einar-triton** [comment]
I am looking into `pub fn leaf_index_to_mt_index_and_peak_index(leaf_index: u64, leaf_count: u64) -> (u64, u32)`.

**Comment by einar-triton** [comment]
`leaf_index_to_mt_index_and_peak_index` was implemented using loops in #23.
Next up: implement `leaf_index_to_mt_index_and_peak_index` using `popcount`.
