### ISSUE TITLE
Test the `value` method on the `BFieldElement` struct

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/tasm-lang#34]
I added support for the `value` function in 9f76de7af106501fc802e841719619049473148b, but I didn't test it properly.

**Comment by Sword-Smith** [comment]
@junkicide have a look at this :)

**Comment by junkicide** [comment]
might start with this one

**Comment by Sword-Smith** [comment]
Solved by 0398184e57da3889fb1ff8a308785dfe3d344e0c
